### ISSUE TITLE
No dependencies transformer incorrectly handles renames from longer to shorter package names

### ISSUE THREAD

**Issue by ropalka** [wildfly-extras/batavia#30]
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException
	at java.lang.System.arraycopy(Native Method)
	at org.wildfly.transformer.nodeps.TransformerImpl.applyPatches(TransformerImpl.java:253)
	at org.wildfly.transformer.nodeps.TransformerImpl.transform(TransformerImpl.java:191)
	at org.wildfly.transformer.nodeps.TransformerImpl.transform(TransformerImpl.java:116)
	at org.wildfly.transformer.tool.shared.Common.transformJarFile(Common.java:89)
	at org.wildfly.transformer.tool.cmdline.Main.main(Main.java:45)

**Comment by scottmarlow** [comment]
Good catch!
