### ISSUE TITLE
ASM transformer needs NestHost support

### ISSUE THREAD

**Issue by scottmarlow** [wildfly-extras/batavia#49]
To reproduce from wildfly/dist/target/wildfly-20.0.0.Final-SNAPSHOT/modules/system/layers/base/org/bouncycastle/main:
```
ee8jar2ee9.sh bcprov-jdk15on-1.65.jar /tmp
inputs:
jarname=bcprov-jdk15on-1.65.jar /tmp
Exception in thread "main" java.lang.UnsupportedOperationException: This feature requires ASM7
        at org.objectweb.asm.ClassVisitor.visitNestHost(ClassVisitor.java:150)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:550)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:400)
        at org.wildfly.transformer.asm.TransformerImpl.transform(TransformerImpl.java:99)
        at org.wildfly.transformer.asm.TransformerImpl.transform(TransformerImpl.java:627)
        at org.wildfly.transformer.tool.api.ToolUtils.transformJarFile(ToolUtils.java:104)
        at org.wildfly.transformer.tool.cli.Main.main(Main.java:45)
```

**Comment by scottmarlow** [comment]
[rename ee8jar2ee9.txt => ee8jar2ee9.sh](https://github.com/wildfly-extras/batavia/files/4718903/ee8jar2ee9.txt)
